# ==============================================================================
# Read iter0 results for one basin
#
# The current workflow stores iter0 as a list containing normalized parameters
# and calibration KGE values.
# ==============================================================================

read_iter0_for_basin <- function(paths, basinID, zDecision, parameter_names) {
  
  f <- file.path(
    paths$iter0,
    paste0("zDecision_", zDecision),
    basinID,
    paste0("iter0_", basinID, "_zDec_", zDecision, ".RData")
  )
  
  x <- load_rdata_single(f)
  
  if (!is.list(x) || is.data.frame(x) || is.null(x$params_normalized)) {
    stop("Unrecognized iter0 format for basin ", basinID)
  }
  
  p <- as.data.frame(x$params_normalized)
  names(p) <- paste0("p", seq_along(parameter_names))
  p$KGE <- x$KGE_calibration
  p$source_step <- -1L
  
  p
}


# ==============================================================================
# Build the emulator training dataset
#
# The initial iter0 ensemble is combined with successful FUSE evaluations from
# previous refinement steps. Only candidates generated by the current emulator
# type are added, so each emulator is refined using its own proposed parameter
# sets.
# ==============================================================================

build_emulator_dataset <- function(paths, experiment_dir, basin_ids, zDecision, iStep,
                                   emulator_type, attributes, attribute_names,
                                   parameter_names, nCandidates) {
  
  pieces <- vector("list", length(basin_ids))
  colsX <- paste0("p", seq_along(parameter_names))
  
  for (b in seq_along(basin_ids)) {
    
    id <- as.character(basin_ids[b])
    
    row <- which(as.character(attributes$ID) == id)
    
    if (length(row) != 1L) {
      stop("Expected exactly one attributes row for basin ", id)
    }
    
    att <- attributes[row, attribute_names, drop = FALSE]
    
    # Start from the immutable initial FUSE ensemble.
    p <- read_iter0_for_basin(paths, id, zDecision, parameter_names)
    
    # Add successful candidates evaluated during earlier refinement steps.
    if (iStep > 0L) {
      
      for (s in 0:(iStep - 1L)) {
        
        f <- file.path(
          experiment_dir, "outputs", paste0("zDecision_", zDecision),
          "train", id, paste0("candidates_step_", s, ".RData")
        )
        
        if (!file.exists(f)) {
          stop("Missing previous-step training candidates: ", f)
        }
        
        ps <- load_rdata_single(f)
        
        ps <- ps[
          ps$emulator == emulator_type & is.finite(ps$KGEc),
          ,
          drop = FALSE
        ]
        
        if (nrow(ps)) {
          
          # Retain the candidates ranked highest by the emulator prediction.
          ps <- ps[order(ps$eNKGE, decreasing = TRUE, na.last = NA), , drop = FALSE]
          ps <- head(ps, nCandidates)
          
          add <- ps[, c(colsX, "KGEc"), drop = FALSE]
          names(add)[names(add) == "KGEc"] <- "KGE"
          add$source_step <- s
          
          p <- rbind(p, add)
        }
      }
    }
    
    # Static catchment attributes are repeated for every parameter set belonging
    # to the basin.
    p <- cbind(p, att[rep(1, nrow(p)), , drop = FALSE])
    p$ID <- id
    
    pieces[[b]] <- p
  }
  
  out <- do.call(rbind, pieces)
  
  # The emulator is trained against normalized KGE.
  out$NKGE <- nkge(out$KGE)
  
  rownames(out) <- NULL
  
  out
}